# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jetra.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("jetra.proto", :syntax => :proto3) do
    add_message "jetra.grpc.JetraRequest" do
      optional :route, :string, 1
      optional :params, :string, 2
    end
    add_message "jetra.grpc.JetraResponse" do
      optional :status, :int32, 1
      optional :body, :string, 2
    end
  end
end

module Jetra
  module Grpc
    JetraRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("jetra.grpc.JetraRequest").msgclass
    JetraResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("jetra.grpc.JetraResponse").msgclass
  end
end
