# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("demo.proto", :syntax => :proto3) do
    add_message "jetra.grpc_demo.Product" do
      optional :id, :uint32, 1
      optional :name, :string, 2
      optional :price, :float, 3
    end
  end
end

module Jetra
  module GrpcDemo
    Product = Google::Protobuf::DescriptorPool.generated_pool.lookup("jetra.grpc_demo.Product").msgclass
  end
end
